### ISSUE TITLE
Toolkit set up needs to be updated

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.tcp#1]
I am looking around and noticed that the project is not set up based on standard repository guideline:

See this toolkit for example:
https://github.com/IBMStreams/streamsx.inet
-  The toolkit project should be at the root of your repository.  Currently, it is stored under: MultiConnectionTCPServer/Toolkit directory.
-  Samples directory should also be at the root of the repository.  Currently, they are in MultiConnectionTCPServer/Samples directory.
-  Doc content should not be checked into the repository.  Please set up proper .gitignore file.
-  Please update copyrights for all files... We use the following copyright:

Copyright (C) 2015, International Business Machines Corporation. 
All Rights Reserved.

**Comment by chanskw** [comment]
Hi Senthil,
Any news here?  Is it alright if we try to restructure this toolkit?  
Thanks...
Samantha

**Comment by chanskw** [comment]
Other problems with this set up include:
- The toolkit itself cannot be imported and develop in Streams Studio easily.
- Samples cannot be imported into Studio to be developed easily.

I tried changing the set up... I had to update a couple of places in the Makefile to get it to work.  But the toolkit itself has no hard dependency for this directory structure.

**Comment by nysenthil** [comment]
Hi Samantha,
As we discussed today, you can try on your local machine to restructure as you suggested. Once it works, we can review it before moving it to GitHub. As I mentioned earlier, this particular toolkit has been used by several of our strategic paying customers for the past 3 years.

-- Senthil.

**Comment by chanskw** [comment]
Yep understood.  I am only documenting what needs to get updated.

I have made the changes to make this work.  But I have a question about how we want to move forward with this toolkit.  Because you have existing customers using this, how do they feel about the toolkit breaking source compatibility.

Couple of things I had to change:
1)  I had to rename the toolkit to com.ibm.streamsx.tcp - the current name does not conform the toolkit naming standard.
2)  Streams 4.0 updated the boost library and the toolkit no longer builds with Streams 4.0.  I had to change the operator code to make it build with the Streams-boost library.  This change will not work in previous version of Streams.
3)  Because we are moving to 4.0, We need to bump the toolkit version number to 2.0 and required Streams verson for 4.0 - This could cause build issues with exisitng customers.

Given that this is an open-source toolkit, my recommendation is to break compatibility now when we move to support 4.0.

But to support existing customer, we may want to create a branch for pre-4.0 customers.

How do you feel about this approach?  I guess I am trying to figure out that if I make the changes to support 4.0, how should we deal with the incompatible changes?

**Comment by nysenthil** [comment]
Hi Samantha,
Existing customers are mostly using the previous version of this toolkit which is available in the dW StreamsExchange. We can use that version to provide support for existing customers. When they migrate to Streams 4.x, they can start using the GitHub version. In addition, there is version 1.0.3 release version tagged in GitHub which clearly says it is meant for Streams 3.x. Going forward, the new tags will be made to work only with Streams 4.x. I believe that should cover both the Streams 3.x and 4.x users who would be interested in using this toolkit.

**Comment by chanskw** [comment]
Perfect!  I will make the changes in the master branch and create a pull request when ready.
we can review and discuss if the changes are good.

**Comment by chanskw** [comment]
Created pull request... please review and merge.
Let me know if you have question.. or look at my repo to see how I refactored the code.

**Comment by chanskw** [comment]
Fixed... closing
