### ISSUE TITLE
Nominate Leonid Gorelik as committer to streamsx.tcp project

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.tcp#13]
I would like to nominate @leongor as committer to streamsx.tcp project.

Leonid has added a major feature into the toolkit operator (full duplex support).  The contribution is of high-quality and he has demonstrated a good understanding of the code base.

Please vote.

**Comment by nysenthil** [comment]
Hi Samantha,
I support Leonid to be a committer for the streamsx.tcp toolkit.

-- Senthil.

**Comment by chanskw** [comment]
Voting done.  Added Leonid as committer.
