### ISSUE TITLE
TCPServer does not disconnect client after maxUnreadResponseCount

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.tcp#16]
I have a TCP client that will set up a duplex connection, send a request but not read a response.

I set the TCPServer like this:

```
    stream<TcpServerStrT> TcpServerOp = TCPServer(Functor_3_out0 as inPort0Alias)
    {
        param
            port : 22222u ;
            threadPoolSize : 20u ;
            maxUnreadResponseCount : 10000u ;
            disableDuplexConnection: shutdown;
    }
```

The first time I launched this client, the server will detect that the num of unread response has exceeded 10000 (but it went all the way up to > 30000 messages before it detected it).. and the connection was closed.

The second time I launched the same application, the server never disconnects the client.

**Comment by chanskw** [comment]
I believe this code is problematic:

 bool TCPConnection::shutdown_send_once(bool makeConnReadOnly)
    {
        static bool shutdown_send_op = shutdown_send(makeConnReadOnly);
        return shutdown_send_op;
    }

In this member function, we are declaring a static variable to send for shutdown_send call.  With a static variable, this variable is initialized only once for the process, even though there are multiple instances of the same class.  As a result, this will only get called once.  Subsequent connections will not be told to shutdown even when the method is called.  

I removed the static keyword, and it seems to have solved the problem. But I do not understand why this is made static in the first place.

**Comment by chanskw** [comment]
I believe this is made static to ensure that we are only going to make the connection read-only once.  However, because we are using the static keyword, it seems to me that we are making the assumption that the server will only ever handle a single connection.  I do not think it is correct.

I have modified the connection.h and connection.cpp code in the substream to detect if the connection has been previously shutdown and it has, do not call disconnect again.

Please review the changes and see if it works for you.

**Comment by leongor** [comment]
Fixed - closing the issue.
