### ISSUE TITLE
block format pre-appending unwanted buffer length

### ISSUE THREAD

**Issue by siegenth** [IBMStreams/streamsx.tcp#17]
I'm using the TCPServerTransmit  operator to receive notification when a client connects and transmit BLOBs. The operator is adding and extra 8 bytes to the front of the  message that I'm sending, the 8 bytes is the length of the message that I'm transmitting.

What I'm attempting to send....

```
00000000: 1718 0101 4616 0000 8799 6c55 0000 0000  ....F.....lU....
00000010: 0000 0000 0f27 0000 0100 0100 0500 0700  .....'..........
```

What is being sent: 

```
00000000: 0000 0000 0000 1646 1718 0101 4616 0000  .......F....F...
00000010: 8799 6c55 0000 0000 0000 0000 0f27 0000  ..lU.........'..
```

Below is my invocation of the Operator.

```
(stream<TcpServerStrT> TCPServer_18_out0 ; stream<TcpServerStatusT>
            TCPServerStatus) as TCPServerTransmit = TCPServer(Delay_21_out0) {
            param
                port : $CLIENT_PORT ;
                threadPoolSize : 1u ;
                connectionCap : 5u ;
                format : TCPServer.block ;
                blockSize : 100000u ;
                address : $CLIENT_ADDRESS ;}
```

Have I missed or misused a parameter? Can I disable the length from being sent?     

_A little context_
In this application Streams is acting as a multiplexer to a hardware monitor. The monitor transmits wave form data via TCP to Steams. Streams pushes the data to a database and multiplexes it to downstream clients that have connected to Streams.

The 'What I'm attempting to send...' above is actually what I'm getting from the hardware. Both data examples are captured using netcat.

**Comment by leongor** [comment]
When working TCP you must tell other side where your message ends because TCP protocol can decide to send it in multiple packets - there is no promise that even if it's a small message, it'll be sent in one packet.
So, there are 2 options to choose:
1. 'format : line'
Requires data to be 'rstring' format and appends new line at the end if it doesn't exist.
2. 'format : block'
Requires data to be 'blob' format and appends it's size at the beginning.

Thus a client always can figure out boundaries of an actual message.

**Comment by siegenth** [comment]
Seems like we need a third format of 'raw' that will send the blob without the size. 

The data that I'm getting from the hardware has a sync [17,18] followed by a version, type and size (swapped). I code for the situation packets can be broken at any point.

**Comment by leongor** [comment]
I see your point and suggest to vote to add the 'row' format option.
+1 from my side.

**Comment by leongor** [comment]
I've added raw format.
To enable it: change TcpServerBlobT to TcpServerRawT type when sending stream to TCPServer input port.

**Comment by leongor** [comment]
Closing the issue - the required functionality added.
