### ISSUE TITLE
com.ibm.streamsx.tcp/doc/spldoc/index.html is missing

### ISSUE THREAD

**Issue by aqing1987** [IBMStreams/streamsx.tcp#18]
Dear there, 
I cannot find the index.html as descried in streamsx.tcp/com.ibm.streamsx.tcp/README

as the quote
"Description about this TCPServer operator is well documented in the following web browser friendly HTML file:
com.ibm.streamsx.tcp/doc/spldoc/index.html"

Hope you can fix it.

BRs,
Rex

**Comment by markheger** [comment]
SPLDoc added to iopages
http://ibmstreams.github.io/streamsx.tcp/doc/spldoc/html/tk$com.ibm.streamsx.tcp/tk$com.ibm.streamsx.tcp.html
