### ISSUE TITLE
Unable to compile the toolkit by using Make.

### ISSUE THREAD

**Issue by aqing1987** [IBMStreams/streamsx.tcp#19]
Hi there, 

I use emacs for work, so I compile as described in README, 
"To build the toolkit, type:
cd com.ibm.streamsx.tcp/
make"

But I got the wrong msg as below:

rex@xx:~/workspace/open-src/streamsx.tcp/com.ibm.streamsx.tcp$ make
cd impl; make all
make[1]: Entering directory `/home/rex/workspace/open-src/streamsx.tcp/com.ibm.streamsx.tcp/impl'
Compiling src/mcts/server.cpp ...
mkdir   -p    ./lib
/bin/sh: 1: /bin/dst-pe-pkg-config.sh: not found
In file included from src/mcts/server.cpp:8:0:
include/mcts/server.h:14:34: fatal error: streams_boost/asio.hpp: No such file or directory
 #include <streams_boost/asio.hpp>
                                  ^
compilation terminated.
make[1]: *** [lib/server.o] Error 1
make[1]: Leaving directory`/home/rex/workspace/open-src/streamsx.tcp/com.ibm.streamsx.tcp/impl'
make: **\* [mctsLib] Error 2

**Comment by leongor** [comment]
Hi,

$STREAMS_INSTALL environment variable must exist and point to Streams install location.
Please, run before make:
source <Streams Install Dir>/bin/streamsprofile.sh

**Comment by aqing1987** [comment]
Dear there,

You mean I should install Streams first ? the InfoSphere Streams ?
I just get the info from 
http://www.ibm.com/developerworks/downloads/im/streams/
&& only trial version enable. So is there a free version for ubuntu ?

BRs,
Rex

**Comment by leongor** [comment]
Actually it's not trial - it's InfoSphere Streams Quick Start edition.
That means you can use it freely, but only for developing purposes.
No Ubuntu version - the available options are: Centos/Redhat 6/7, SLES 11.

**Comment by leongor** [comment]
Closing this issue.

**Comment by aqing1987** [comment]
Got it.
leongor, tks a million!
