### ISSUE TITLE
Can't compile project using TCPServer

### ISSUE THREAD

**Issue by AdiBg** [IBMStreams/streamsx.tcp#2]
getting error:
/usr/bin/ld: cannot find -lstreams.spl.multiconnection.tcp.server

**Comment by nysenthil** [comment]
Hi,
I just now downloaded the tar.gz file of this toolkit from the releases section and tested it on a RHEL6 machine running Streams 3.x. Everything worked fine. (Please note that this toolkit has not yet been migrated to Streams 4.x and I will do it next week).

Please tell me whether you followed the exact steps 1 & 2 as described in streamsx.tcp-1.0.3/MultiConnectionTCPServer/README.

Regards,
Senthil.

**Comment by chanskw** [comment]
I run into the same problem when trying this with Studio and I am using Streams 4.x.

**Comment by chanskw** [comment]
This is an issue when the underlying library is not built before trying to the sample
I updated the Makefile as part of #1 to simplify the build process.

**Comment by AdiBg** [comment]
Thank you!
Unfortunately after I posted this issue I understood that the toolkit doesn't suit my needs.
I needed a client tcp that can read and write in one operator from one socket. Wrote it myself eventually.
But it is good to know that your toolkit also can use me know.

בתאריך 1 במאי 2015 12:21 לפנה״צ,‏ Samantha Chan notifications@github.com כתב:

This is an issue when the underlying library is not built before trying to the sample
I updated the Makefile as part of #1https://github.com/IBMStreams/streamsx.tcp/issues/1 to simplify the build process.

**Comment by chanskw** [comment]
Fixed as part of #1 to simplify build process.
