### ISSUE TITLE
TCPSource and TCPServer operators in standalone error. 

### ISSUE THREAD

**Issue by siegenth** [IBMStreams/streamsx.tcp#23]
When I run TCPSource and TCPServer run in the same standalone. I get an 
error when TCPServer is writing, this is the error : 

```
17 Sep 2015 17:24:37.323 [62567] ERROR #splapptrc,J[0],P[0],TCPServerTransmit,TCPServer M[TCPServerTransmit.cpp:handleError:173]  - responseError: Unable to send data to 172.16.49.1:56590
Software caused connection abort
```

When I run in distributed no problems. I an imagine it's not supported. 

Thanks

**Comment by leongor** [comment]
Hmm, never ran TCPServer and TCPSource together - usually they are mutually exclusive :)
Let me check.

**Comment by leongor** [comment]
I've successfully fused together both operators - works smoothly.
Do you want to post your SPL code?

**Comment by leongor** [comment]
@siegenth I'm closing this issue. If you still have this problem, please reopen it and provide additional info.
