### ISSUE TITLE
Broadcast response feature proposal

### ISSUE THREAD

**Issue by leongor** [IBMStreams/streamsx.tcp#24]
I propose to add broadcasting response functionality.
It could be very useful when there are multiple passive clients that should be updated with the same tuple.
Instead of managing map of clients in SPL and sending the same tuple in the loop, just set TCPServer broadcastResponse parameter to true.

**Comment by apyasic** [comment]
+1

**Comment by nysenthil** [comment]
+1

**Comment by leongor** [comment]
Added broadcastResponse parameter.

**Comment by leongor** [comment]
Closing this issue.
