### ISSUE TITLE
FullDuplex crashes, on receiving NULL string to the port

### ISSUE THREAD

**Issue by pv781t** [IBMStreams/streamsx.tcp#26]
Hi,

Recently the issue was observed, where the Full Duplex crashes if "NULL" string is sent to its port.
To reproduce the issue:
1. Start any test program with FullDuplex (FD)
2. Make sure that the connection to the FD port has been established with netstat.
3. Send some "NULL" value to the port as  
                nc -n  host_name port_name 
4. Monitor the port with netstat - the status changes to WAITING, then FD port becomes unavailable
5. Full Duplex throws the exception - see the attached file.

[pec.pe682.zip](https://github.com/IBMStreams/streamsx.tcp/files/105414/pec.pe682.zip)

Regards,    pv781t

**Comment by leongor** [comment]
There is a  fix for this issue - please, download the latest toolkit version.

**Comment by pv781t** [comment]
The same scenario fails the standard toolkit com.ibm.streams.tcp::TCPServer(), so is there a fix for that as well?

**Comment by pv781t** [comment]
Hi,

The additional issue I observed is that also fails the standard toolkit com.ibm.streams.tcp::TCPServer().
Is there a resolution for that aswell?

Regards, Pavel

**Comment by pv781t** [comment]
Ok, the new version works fine. Thank you.

P.S.
By com.ibm.streams.tcp::TCPServer() I mentioned the half duplex operator, which is not the standard one.
