### ISSUE TITLE
Does TCPServer for streamx.tcp work for half duplex client?

### ISSUE THREAD

**Issue by SanjuDabi** [IBMStreams/streamsx.tcp#27]
For half duplex clients we used toolkit MultiConnectionTCPServer, that was obtained from IBM developerWorks.
https://www.ibm.com/developerworks/community/files/app#/file/0e0078a4-7c95-4efb-bd3c-a90689c6d177
Per documentation on this website this is not more supported and points to streamx.tcp which is for full duplex.

We need to know if we can use this TCPServer also for half duplex Clients? Or can it have some issues?

**Comment by nysenthil** [comment]
Hi Sanju,
We moved the toolkit you used earlier from IBM dW to this github. 80% of this toolkit is still that same code and we further enhanced it to support full duplex. You can continue to use what you already have if you only want half duplex or you can consider upgrading to the newer version available here in github if you want half duplex, full duplex and a few other new enhancements.

**Comment by leongor** [comment]
Yes, it is the same toolkit. The duplex functionality is optional and enabled only if an input port of the operator in use.

-----Original Message-----
