### ISSUE TITLE
Too many CLOSE_WAITs on TCPServer port

### ISSUE THREAD

**Issue by SanjuDabi** [IBMStreams/streamsx.tcp#29]
We often run into situation where were see too many CLOSE_WAITs on TCPServer port
Client says they do not see ACK received when FIN is sent.

tcp        0      0 130.5.109.93:64557          130.5.112.168:47721         SYN_RECV
tcp        0      0 130.5.109.93:64557          130.5.112.168:47730         SYN_RECV
tcp      238      0 130.5.109.93:64557          130.5.112.168:47664         CLOSE_WAIT
tcp        1      0 130.5.109.93:64557          130.5.112.168:47496         CLOSE_WAIT
tcp      234      0 130.5.109.93:64557          130.5.112.168:47680         CLOSE_WAIT
tcp      234      0 130.5.109.93:64557          130.5.112.168:47687         CLOSE_WAIT
tcp      250      0 130.5.109.93:64557          130.5.112.168:47634         CLOSE_WAIT
tcp      228      0 130.5.109.93:64557          130.5.112.168:47651         CLOSE_WAIT
tcp      238      0 130.5.109.93:64557          130.5.112.168:47626         CLOSE_WAIT

How can we get rid of connections showing in CLOSE_WAIT?
Is there any parameter that can be set to terminate these connections within 1 minute on full duplex port?

Also I suppose once we reach limit of CLOSE_WAIT that equals maxConnections, no further connections will be allowed on port, correct? 

What is max value that should be used for maxConnections? Any limits?

**Comment by leongor** [comment]
@SanjuDabi Sorry for a delay. If you see  CLOSE_WAIT states, that means you client asked TCPServer to close a connection, but didn't close the socket after that. So from OS point of view it's still alive.
Usually it happens when the client program terminates unexpectedly.
The max number of connection defined by 'connectionCap' parameter. Further connections will be refused.

**Comment by leongor** [comment]
Closing the issue.
