### ISSUE TITLE
Unable to compile toolkit in Streams v4.0

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.tcp#3]
When trying to build toolkit, got the following error:
[streamsadmin@streamsqse impl]$ make
Compiling src/mcts/server.cpp ...
mkdir   -p    ./lib
src/mcts/server.cpp: In constructor ‘mcts::TCPServer::TCPServer(const std::string&, uint32_t, size_t, size_t, uint32_t, mcts::outFormat_t, mcts::DataHandler::Handler, mcts::InfoHandler::Handler)’:
src/mcts/server.cpp:50: error: ‘class streams_boost::asio::ip::tcp::acceptor’ has no member named ‘io_service’
make: **\* [lib/server.o] Error 1

Problem is that the boost library in Streams has been updated in v4.0.

We need to update server.cpp to call get_io_service() at line 50 instead:
streams_boost::asio::ip::tcp::resolver resolver(acceptor_.get_io_service());

After making this change, I am able to build the toolkit at the command line.

**Comment by chanskw** [comment]
Fixed as part of #1

**Comment by chanskw** [comment]
Keeping this opened as we have reverted back to 3.x.

**Comment by markheger** [comment]
no issue with Streams 4.x
