### ISSUE TITLE
Separating release in multiple archives

### ISSUE THREAD

**Issue by leongor** [IBMStreams/streamsx.tcp#31]
I suggest to have multiple archives in each release.
Instead of putting the whole repo to one archive, just have one for the toolkit itself, one for samples and if toolkit has additional builds like compiled libraries in different environments, it can be added too.

**Comment by chanskw** [comment]
Are you suggesting that the compiled libraries will be in a different archive and people can download them separately?  So there will be a set up step to move these libraries into the toolkit?

**Comment by chanskw** [comment]
And what is the reason for separating out the samples... in thinking about this more, would that make the installation of toolkit a bit more difficult?

**Comment by leongor** [comment]
IMHO - no and no.
Because samples are packaged outside of the toolkit there is no benefit if you download them together or separately. But if you want to download only the toolkit (as a part of some solution installation in some project) it's more convenient then. Additionally, you can package the toolkit as a generic one (com.ibm.streamsx.tcp_2.0.tar.gz - no precompiled libs inside) or for a specific environment (com.ibm.streamsx.tcp_2.0.el7.tar.gz - with precompiled libs for RH7 inside).

**Comment by chanskw** [comment]
So, for a specific release, would I have the following packages?

com.ibm.streamsx.tcp_2.0.tar.gz - generic package that has no libraries / samples - with instructions on how to build libraries for specific platforms.
com.ibm.streamsx.tcp._2.0.el7.targ.gz - package including all libraries without samples
com.ibm.streamsx.tcp.samples_2.0.tar.gz - include just the samples

Is this the proposal?

**Comment by leongor** [comment]
Yes, except I would suggest that samples will be named samples_2.0.tar.gz, because it's just an archive holding multiple sample toolkits together.

-----Original Message-----

**Comment by chanskw** [comment]
Ok +1.

I am not 100% sure about breaking out the samples package.  But I can see that it will make the samples more easily discoverable.  Therefore, I support this change.  I would suggest that we add descriptions on how to download the samples so people know that it's a separate download.

**Comment by leongor** [comment]
Published a [new v2.0 release](https://github.com/IBMStreams/streamsx.tcp/releases/tag/v2.0).
