### ISSUE TITLE
Feature request - Input port with IP and port attribues.

### ISSUE THREAD

**Issue by siegenth** [IBMStreams/streamsx.tcp#33]
The operator is being used to monitor power line phasor data, lots of realtime data. Works great, so well that they want to expand the usage to many phasors. Configuring the various ip/address for the 
different tcp protocols that we're support was turning into a spreadsheet nightmare. 

The phasor gang came up with the solution: as the system comes up a central authority determines what ports are to be monitored. The information is sent through a TCP port. 

Currently the port is set with a parameters, I'd like to modify the operator to have an optional input port.  The port would only receive one tuple, with a ip/port. Upon receipt of the the tuple it would use the tuple attributes to open a new connection.  Subsequent processing would proceed as it does now.

Question:
Does this sound reasonable?  What have I missed. 
Any chance you'd make this modification in not to distant future?

**Comment by leongor** [comment]
It sounds as a good enhancement for the toolkit.
Do you see it to be like FileSource operator?
If parameters address/port do not present then an optional input port is expected with such pair of attributes.
Every new pair is going to add another port listener without affecting the existing ones.
Do we want to vote for it?

**Comment by leongor** [comment]
@siegenth Actually there is one problem - we already have an optional input port in TCPServer operator! It serves duplex TCP connections.
We can have two optional input ports - one for duplex connections and one for new dynamic connections. The difference between them will be SPL schema. Does it sounds reasonable?
Overall we don't want to make a use of TCPServer too complex.

**Comment by siegenth** [comment]
@leongor I agree with the adding another optional input port. Overlaying  duplex and dynamic and on the same port would make it more complex. Especially if have duplex and dynamic functionality in the same operator. 

1+ for an additional input port

**Comment by leongor** [comment]
@chanskw has suggested a better idea. Instead of messing with multiple optional input ports we can add an additional action attribute like enum{RESPONSE,LISTEN}. Such method is used in streams.messaging toolkit. For me it sounds better, but it breaks the current SPL schema and will require to adapt existing SPL code.
I suggest to vote again.
+1 for the additional attribute.

**Comment by siegenth** [comment]
@leongor and @chanskw : Is an example from the messaging toolkit's the 'action' attribute [here](http://ibmstreams.github.io/streamsx.messaging/com.ibm.streamsx.messaging/doc/spldoc/html/index.html) ?

I believe this mean we'll be adding a enumerated action attribute {LISTEN,RESPONSE} to TcpServerStrT, TcpServerBlobT, TcpServerStatusT and TcpServerRaw? 

**An example:**
In the instance that tuple was received with a value of action:LISTEN,address:9.0.0.22, port:13. 
- it's an error to have the port parameter
- it's an error to have the address parameter set

When the tuple arrives on the input port 1, the connection is established to 9.0.0.22:13. 
- If any other tuples arrive they are ignored.
- Only one packet on input port 1 will be processed in this configuration.

**Comment by siegenthIbm** [comment]
+1 for additional attribute

**Comment by rhaenggi** [comment]
+1 for additional attribute

**Comment by leongor** [comment]
I've added this feature and published new v2.1:
[generic version (needs build)](https://github.com/IBMStreams/streamsx.tcp/releases/download/v2.0/com.ibm.streamsx.tcp_2.0.tar.gz)
[rhel7 version (pre-built)](https://github.com/IBMStreams/streamsx.tcp/releases/download/v2.0/com.ibm.streamsx.tcp_2.0.el7.tar.gz)

New 'event' attribute of type enum{LISTEN,RESPONSE} was added to the input schema.
Any duplicate LISTEN event (with existing addr/port listener) will be ignored and a warning will be issued.
Try it - any feedback is welcome.

Closing this issue.
