### ISSUE TITLE
Input port of TCPServer should be TCPServerStrEventT or TCPServerBlobEventT

### ISSUE THREAD

**Issue by crecoskie** [IBMStreams/streamsx.tcp#37]
- The doc for TCPServer incorrectly says that the input port should be TCPServerStrT or TCPServerBlobT.  Those types do not contain the required "event" attribute required by the CGT, and compiling with an input port of either one of those types will fail.  It should be TCPServerStrEventT or TCPServerBlobEventT
- The various tests/samples under com.ibm.streamsx.tcpclient/application are written assuming that the doc is right, and as such if you try to actually build them they won't compile, because the CGT calls get_event() to get the event attribute, which doesn't exist on the input port.

**Comment by leongor** [comment]
Fixed.
Closing.
