### ISSUE TITLE
Provide full duplex TCPServer

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.tcp#6]
TCPServer is now a source operator.
We need full duplex support so it can go bi-directional.

**Comment by chanskw** [comment]
The current design is this:
1)  We will enhance the TCPServer implementation to provide asynchronous write support
2)  At the operator level, introduce a new input port where user can stream in data.
3)  Input port schema can be one of the following:
  <rstring data, rstring serverHost, uint32 serverPort>  or <blob data, rstring serverHost, uint32 serverPort> - ServerHost and ServerPort is the server that we will send the data to.  User can get this data from the incoming data on the TCPServer.

**Comment by chanskw** [comment]
- Added TCPServerDuplex sample
- Added new input port
- Added in SPL types to help user write application

-> Pushed changes to Leonid's repo

**Comment by chanskw** [comment]
Leonid - 

I tried out the latest code drop.  I created a small Java program that will send and receive message.
I think there is a flush problem in the operator, as the read call never comes back.  The read call only comes back when I cancel the job, which forces the connection to be terminated.

I found this post.. You may want to look at the underlying write code and see.

http://stackoverflow.com/questions/3345309/how-to-flush-the-socket-using-boost

public static void main(String[] args) {
        try {
            Socket socket = new Socket("hostname", 22222);
            BufferedReader inReader = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            BufferedWriter outWriter = new BufferedWriter(new OutputStreamWriter(socket.getOutputStream()));

```
        // take the input tuple
        String line = "Test String";

        // send it through the socket
        outWriter.write(line);
        outWriter.flush();

        // read response from socket
        String response = inReader.readLine();      

        // output response              
        // Create a new tuple for output port 0
       System.out.println(line);


    } catch (UnknownHostException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    } catch (IOException e) {
        // TODO Auto-generated catch block
        e.printStackTrace();
    }

}
```

**Comment by leongor** [comment]
Samantha,

I cannot flush buffer because I don't use buffered API (as you do in this Java test).
I've found 2 typos in this code:
1. Change System.out.println(line) to System.out.println(response) - you will get null as response (because TCPServer didn't send really a response as the request is still not finished)
2. Change "Test String" to  "Test String\n" - then it works (similar to inReader.readLine() that expects to get '\n' as packet delimiter, TCPServer needs it too)

**Comment by leongor** [comment]
You can also run netcat utility to test:
nc <hostname> 22222 <ENTER>
<send any message>
<see response here>

**Comment by chanskw** [comment]
Ok!  got it!  Thanks!

**Comment by chanskw** [comment]
I have written a simple Java operator that is a duplex client.
I managed to establish a duplex communication with the TCPServer operator.  Response is sent back accordingly.

However, if I have two clients connected to the server, the second client will get blank lines as responses.  In some cases, I am getting junk in the first connection too.

**Comment by leongor** [comment]
Introduced a new class AsyncDataItem - sending buffer per async write, not per connection.
The test works well now.

**Comment by chanskw** [comment]
Code Review Meeting - 
- Samantha
- Senthil
- Leonid

Here are comments from the view.
- (Samantha - operator_level) To handle rstring, check if the string ends with newline, if now, add it implicitly.
- (Leonid - ) To handle blob, when the TCPServer sends back a response, prefix the length of the data in the first two bytes and then send the data back.  On the client side, the client deciphers the length from the first two bytes... and then read the buffer based on that length.
- nNumConnections - when a connection is lost / disconnected, we need to decrement the metric value.  This can be done in the destructor of connection.cpp
- In the process method, when we call handleWrite, we want to prevent copying data.
- handleWrite needs to handle string and blob differently.  For blob, we need to prefix it with the lenth of blob data about to send.

**Comment by chanskw** [comment]
I have tried adding the following code to implicitly add a newline character in handleWrite.

I haven't delivered it because I start to question if this is really the right thing to do.  The problem is that I think this introduce a performance penalty for data that already has newline appended at the end.

In this code, we check if the tuple ends with newline. and if not, add it.  This check is done, even for data that already has a newline appended, and introduced performance penalty for every single tuple that is processed.  I propose that we tell user to add the new line as needed and avoid having to do this check.

void MY_OPERATOR::handleWrite(std::string & line, std::string const & ipAddress, uint32_t port)
{
    SPL::blob raw(reinterpret_cast<unsigned char const *>(line.data()), line.size());

```
// TODO:  check if there is a new line
// if there is no newline
// add newline to the end of the blob
if (!streams_boost::algorithm::ends_with(line, "\n"))
{
    raw += atoi("\n");
}

server_.handleWrite(raw, true, ipAddress, port);
```

}

**Comment by chanskw** [comment]
see issue #8

**Comment by leongor** [comment]
Regarding new line I agree - maybe it's overkilling feature. I don't think that the check itself produce performance problems, but not sure how blob handles this "raw += atoi("\n");" - maybe there is memory reallocation here and data is copied eventually.

**Comment by chanskw** [comment]
I do not think doing the check will normally cause performance problem.  But my strategy with the process method is to do minimum and also do minimum method calls.  Calling a method once maybe ok, but calling it a million times in a second will introduce some sort of performance penalty.

I tested the code.  raw+=atoi("\n"); was handled correctly.  I just did not want to do this in the process method for all tuples either.

**Comment by leongor** [comment]
I'm voting to avoid the implicit append of a newline and introduce a new string optional parameter 'eventDelimeter' to provide a user a way to choose any custom tag to append.

**Comment by chanskw** [comment]
+1  agree

**Comment by chanskw** [comment]
This work is completed.
Closing.
