### ISSUE TITLE
Stall connection could cause TCPServer duplex support to slow down

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.tcp#8]
I have three applications:

1)  TCPServerMain - this accepts duplex TCP connection and sends response back.
2)  ManyClientsMain - this has 5 clients, all with duplex communication.  The client continues to send and receive data.  Data received is put to a file.
3)  ManyClientsNoReadMain - this has 1 client.  This client keeps sending requests to TCPServer, but there is no read thread to read the response back from the server.  Connection is kept opened.

When my 3 apps first started running, each client is handling about 2000 tuples per second from the ManyClientsMain application.  I left it running for a while (now it's about 10 min).... I can see that performance on all clients slowly degrade.  I think the problem is that I have a client that just keeps sending request and not reading any response.  And it eventually takes up all the threads / buffers down at the I/O level.

Canceling the ManyClientsNoReadMain job does not improve performance.  This means performance continues to be bad, even after connection to the server is broken.

**Comment by leongor** [comment]
Introduced new threshold parameter: maxUnreadResponseCount.
If a number of unread responses of specific client increases more than maxUnreadResponseCount, then the response part of the connection is disabled.

**Comment by chanskw** [comment]
fixed
